/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.MappingConfigInputOutput;
import org.openapitools.client.model.ModelNodeConfigInputOutput;
import org.openapitools.client.model.OnlinePointConfigInputOutput;
import org.openapitools.client.model.SysCodeConfigInputOutput;

/**
 * AssemblyConfigOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class AssemblyConfigOutput {
  public static final String SERIALIZED_NAME_SYS_CODE_CONFIG = "sysCodeConfig";
  @SerializedName(SERIALIZED_NAME_SYS_CODE_CONFIG)
  private SysCodeConfigInputOutput sysCodeConfig;

  public static final String SERIALIZED_NAME_ONLINE_POINT_CONFIG = "onlinePointConfig";
  @SerializedName(SERIALIZED_NAME_ONLINE_POINT_CONFIG)
  private OnlinePointConfigInputOutput onlinePointConfig;

  public static final String SERIALIZED_NAME_MODEL_NODE_CONFIG = "modelNodeConfig";
  @SerializedName(SERIALIZED_NAME_MODEL_NODE_CONFIG)
  private ModelNodeConfigInputOutput modelNodeConfig;

  public static final String SERIALIZED_NAME_MAPPING_CONFIG = "mappingConfig";
  @SerializedName(SERIALIZED_NAME_MAPPING_CONFIG)
  private MappingConfigInputOutput mappingConfig;


  public AssemblyConfigOutput sysCodeConfig(SysCodeConfigInputOutput sysCodeConfig) {
    
    this.sysCodeConfig = sysCodeConfig;
    return this;
  }

   /**
   * Get sysCodeConfig
   * @return sysCodeConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SysCodeConfigInputOutput getSysCodeConfig() {
    return sysCodeConfig;
  }


  public void setSysCodeConfig(SysCodeConfigInputOutput sysCodeConfig) {
    this.sysCodeConfig = sysCodeConfig;
  }


  public AssemblyConfigOutput onlinePointConfig(OnlinePointConfigInputOutput onlinePointConfig) {
    
    this.onlinePointConfig = onlinePointConfig;
    return this;
  }

   /**
   * Get onlinePointConfig
   * @return onlinePointConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OnlinePointConfigInputOutput getOnlinePointConfig() {
    return onlinePointConfig;
  }


  public void setOnlinePointConfig(OnlinePointConfigInputOutput onlinePointConfig) {
    this.onlinePointConfig = onlinePointConfig;
  }


  public AssemblyConfigOutput modelNodeConfig(ModelNodeConfigInputOutput modelNodeConfig) {
    
    this.modelNodeConfig = modelNodeConfig;
    return this;
  }

   /**
   * Get modelNodeConfig
   * @return modelNodeConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModelNodeConfigInputOutput getModelNodeConfig() {
    return modelNodeConfig;
  }


  public void setModelNodeConfig(ModelNodeConfigInputOutput modelNodeConfig) {
    this.modelNodeConfig = modelNodeConfig;
  }


  public AssemblyConfigOutput mappingConfig(MappingConfigInputOutput mappingConfig) {
    
    this.mappingConfig = mappingConfig;
    return this;
  }

   /**
   * Get mappingConfig
   * @return mappingConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MappingConfigInputOutput getMappingConfig() {
    return mappingConfig;
  }


  public void setMappingConfig(MappingConfigInputOutput mappingConfig) {
    this.mappingConfig = mappingConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssemblyConfigOutput assemblyConfigOutput = (AssemblyConfigOutput) o;
    return Objects.equals(this.sysCodeConfig, assemblyConfigOutput.sysCodeConfig) &&
        Objects.equals(this.onlinePointConfig, assemblyConfigOutput.onlinePointConfig) &&
        Objects.equals(this.modelNodeConfig, assemblyConfigOutput.modelNodeConfig) &&
        Objects.equals(this.mappingConfig, assemblyConfigOutput.mappingConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sysCodeConfig, onlinePointConfig, modelNodeConfig, mappingConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssemblyConfigOutput {\n");
    sb.append("    sysCodeConfig: ").append(toIndentedString(sysCodeConfig)).append("\n");
    sb.append("    onlinePointConfig: ").append(toIndentedString(onlinePointConfig)).append("\n");
    sb.append("    modelNodeConfig: ").append(toIndentedString(modelNodeConfig)).append("\n");
    sb.append("    mappingConfig: ").append(toIndentedString(mappingConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

