/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 生化区值
 */
@ApiModel(description = "生化区值")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class BioValue {
  public static final String SERIALIZED_NAME_BIO_NAME = "bioName";
  @SerializedName(SERIALIZED_NAME_BIO_NAME)
  private String bioName;

  public static final String SERIALIZED_NAME_EXT_INFO = "extInfo";
  @SerializedName(SERIALIZED_NAME_EXT_INFO)
  private Integer extInfo;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private Double value;


  public BioValue bioName(String bioName) {
    
    this.bioName = bioName;
    return this;
  }

   /**
   * 生化区名称 biochemical pool name
   * @return bioName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "生化区名称 biochemical pool name")

  public String getBioName() {
    return bioName;
  }


  public void setBioName(String bioName) {
    this.bioName = bioName;
  }


  public BioValue extInfo(Integer extInfo) {
    
    this.extInfo = extInfo;
    return this;
  }

   /**
   * 生化池序号 biochemical pool index
   * @return extInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "生化池序号 biochemical pool index")

  public Integer getExtInfo() {
    return extInfo;
  }


  public void setExtInfo(Integer extInfo) {
    this.extInfo = extInfo;
  }


  public BioValue value(Double value) {
    
    this.value = value;
    return this;
  }

   /**
   * 值 value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "值 value")

  public Double getValue() {
    return value;
  }


  public void setValue(Double value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BioValue bioValue = (BioValue) o;
    return Objects.equals(this.bioName, bioValue.bioName) &&
        Objects.equals(this.extInfo, bioValue.extInfo) &&
        Objects.equals(this.value, bioValue.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bioName, extInfo, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BioValue {\n");
    sb.append("    bioName: ").append(toIndentedString(bioName)).append("\n");
    sb.append("    extInfo: ").append(toIndentedString(extInfo)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

