/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.TsPair;

/**
 * CatalysisBfOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class CatalysisBfOutput {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private String unit;

  public static final String SERIALIZED_NAME_VALUES_BEFORE = "valuesBefore";
  @SerializedName(SERIALIZED_NAME_VALUES_BEFORE)
  private List<TsPair> valuesBefore = null;

  public static final String SERIALIZED_NAME_VALUES_AFTER = "valuesAfter";
  @SerializedName(SERIALIZED_NAME_VALUES_AFTER)
  private List<TsPair> valuesAfter = null;


  public CatalysisBfOutput code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * 指标代码 indicator code
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "指标代码 indicator code")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public CatalysisBfOutput unit(String unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * 单位 unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单位 unit")

  public String getUnit() {
    return unit;
  }


  public void setUnit(String unit) {
    this.unit = unit;
  }


  public CatalysisBfOutput valuesBefore(List<TsPair> valuesBefore) {
    
    this.valuesBefore = valuesBefore;
    return this;
  }

  public CatalysisBfOutput addValuesBeforeItem(TsPair valuesBeforeItem) {
    if (this.valuesBefore == null) {
      this.valuesBefore = new ArrayList<TsPair>();
    }
    this.valuesBefore.add(valuesBeforeItem);
    return this;
  }

   /**
   * 催化反应前时间序列 time-series result before catalysis
   * @return valuesBefore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "催化反应前时间序列 time-series result before catalysis")

  public List<TsPair> getValuesBefore() {
    return valuesBefore;
  }


  public void setValuesBefore(List<TsPair> valuesBefore) {
    this.valuesBefore = valuesBefore;
  }


  public CatalysisBfOutput valuesAfter(List<TsPair> valuesAfter) {
    
    this.valuesAfter = valuesAfter;
    return this;
  }

  public CatalysisBfOutput addValuesAfterItem(TsPair valuesAfterItem) {
    if (this.valuesAfter == null) {
      this.valuesAfter = new ArrayList<TsPair>();
    }
    this.valuesAfter.add(valuesAfterItem);
    return this;
  }

   /**
   * 催化反应后时间序列 time-series result after catalysis
   * @return valuesAfter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "催化反应后时间序列 time-series result after catalysis")

  public List<TsPair> getValuesAfter() {
    return valuesAfter;
  }


  public void setValuesAfter(List<TsPair> valuesAfter) {
    this.valuesAfter = valuesAfter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalysisBfOutput catalysisBfOutput = (CatalysisBfOutput) o;
    return Objects.equals(this.code, catalysisBfOutput.code) &&
        Objects.equals(this.unit, catalysisBfOutput.unit) &&
        Objects.equals(this.valuesBefore, catalysisBfOutput.valuesBefore) &&
        Objects.equals(this.valuesAfter, catalysisBfOutput.valuesAfter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, unit, valuesBefore, valuesAfter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalysisBfOutput {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    valuesBefore: ").append(toIndentedString(valuesBefore)).append("\n");
    sb.append("    valuesAfter: ").append(toIndentedString(valuesAfter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

