/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ControlOnlinePointOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class ControlOnlinePointOutput {
  public static final String SERIALIZED_NAME_CODES = "codes";
  @SerializedName(SERIALIZED_NAME_CODES)
  private List<String> codes = null;

  public static final String SERIALIZED_NAME_UNITS = "units";
  @SerializedName(SERIALIZED_NAME_UNITS)
  private List<String> units = null;

  public static final String SERIALIZED_NAME_POINT_CODES = "pointCodes";
  @SerializedName(SERIALIZED_NAME_POINT_CODES)
  private List<String> pointCodes = null;

  public static final String SERIALIZED_NAME_NAMES = "names";
  @SerializedName(SERIALIZED_NAME_NAMES)
  private List<String> names = null;

  public static final String SERIALIZED_NAME_DEFAULT_VALUES = "defaultValues";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VALUES)
  private List<Double> defaultValues = null;


  public ControlOnlinePointOutput codes(List<String> codes) {
    
    this.codes = codes;
    return this;
  }

  public ControlOnlinePointOutput addCodesItem(String codesItem) {
    if (this.codes == null) {
      this.codes = new ArrayList<String>();
    }
    this.codes.add(codesItem);
    return this;
  }

   /**
   * 系统点位列表 system point codes/indicators
   * @return codes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "系统点位列表 system point codes/indicators")

  public List<String> getCodes() {
    return codes;
  }


  public void setCodes(List<String> codes) {
    this.codes = codes;
  }


  public ControlOnlinePointOutput units(List<String> units) {
    
    this.units = units;
    return this;
  }

  public ControlOnlinePointOutput addUnitsItem(String unitsItem) {
    if (this.units == null) {
      this.units = new ArrayList<String>();
    }
    this.units.add(unitsItem);
    return this;
  }

   /**
   * 单位列表 units
   * @return units
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单位列表 units")

  public List<String> getUnits() {
    return units;
  }


  public void setUnits(List<String> units) {
    this.units = units;
  }


  public ControlOnlinePointOutput pointCodes(List<String> pointCodes) {
    
    this.pointCodes = pointCodes;
    return this;
  }

  public ControlOnlinePointOutput addPointCodesItem(String pointCodesItem) {
    if (this.pointCodes == null) {
      this.pointCodes = new ArrayList<String>();
    }
    this.pointCodes.add(pointCodesItem);
    return this;
  }

   /**
   * 在线点位列表 corresponding online point codes
   * @return pointCodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "在线点位列表 corresponding online point codes")

  public List<String> getPointCodes() {
    return pointCodes;
  }


  public void setPointCodes(List<String> pointCodes) {
    this.pointCodes = pointCodes;
  }


  public ControlOnlinePointOutput names(List<String> names) {
    
    this.names = names;
    return this;
  }

  public ControlOnlinePointOutput addNamesItem(String namesItem) {
    if (this.names == null) {
      this.names = new ArrayList<String>();
    }
    this.names.add(namesItem);
    return this;
  }

   /**
   * 点位描述 corresponding names
   * @return names
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "点位描述 corresponding names")

  public List<String> getNames() {
    return names;
  }


  public void setNames(List<String> names) {
    this.names = names;
  }


  public ControlOnlinePointOutput defaultValues(List<Double> defaultValues) {
    
    this.defaultValues = defaultValues;
    return this;
  }

  public ControlOnlinePointOutput addDefaultValuesItem(Double defaultValuesItem) {
    if (this.defaultValues == null) {
      this.defaultValues = new ArrayList<Double>();
    }
    this.defaultValues.add(defaultValuesItem);
    return this;
  }

   /**
   * 默认值/阈值 default values/thresholds
   * @return defaultValues
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "默认值/阈值 default values/thresholds")

  public List<Double> getDefaultValues() {
    return defaultValues;
  }


  public void setDefaultValues(List<Double> defaultValues) {
    this.defaultValues = defaultValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControlOnlinePointOutput controlOnlinePointOutput = (ControlOnlinePointOutput) o;
    return Objects.equals(this.codes, controlOnlinePointOutput.codes) &&
        Objects.equals(this.units, controlOnlinePointOutput.units) &&
        Objects.equals(this.pointCodes, controlOnlinePointOutput.pointCodes) &&
        Objects.equals(this.names, controlOnlinePointOutput.names) &&
        Objects.equals(this.defaultValues, controlOnlinePointOutput.defaultValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codes, units, pointCodes, names, defaultValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControlOnlinePointOutput {\n");
    sb.append("    codes: ").append(toIndentedString(codes)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    pointCodes: ").append(toIndentedString(pointCodes)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    defaultValues: ").append(toIndentedString(defaultValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

