/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.TsPair;

/**
 * 控制项数据
 */
@ApiModel(description = "控制项数据")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class ControlItem {
  public static final String SERIALIZED_NAME_ITEM_NAME = "itemName";
  @SerializedName(SERIALIZED_NAME_ITEM_NAME)
  private String itemName;

  public static final String SERIALIZED_NAME_SUGGESTED_VALUE = "suggestedValue";
  @SerializedName(SERIALIZED_NAME_SUGGESTED_VALUE)
  private Double suggestedValue;

  public static final String SERIALIZED_NAME_TS_DATA = "tsData";
  @SerializedName(SERIALIZED_NAME_TS_DATA)
  private List<TsPair> tsData = null;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private String unit;


  public ControlItem itemName(String itemName) {
    
    this.itemName = itemName;
    return this;
  }

   /**
   * 控制项 control item name
   * @return itemName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "控制项 control item name")

  public String getItemName() {
    return itemName;
  }


  public void setItemName(String itemName) {
    this.itemName = itemName;
  }


   /**
   * 建议值 suggested value
   * @return suggestedValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "建议值 suggested value")

  public Double getSuggestedValue() {
    return suggestedValue;
  }




  public ControlItem tsData(List<TsPair> tsData) {
    
    this.tsData = tsData;
    return this;
  }

  public ControlItem addTsDataItem(TsPair tsDataItem) {
    if (this.tsData == null) {
      this.tsData = new ArrayList<TsPair>();
    }
    this.tsData.add(tsDataItem);
    return this;
  }

   /**
   * 时间序列值-图表显示 suggested time-series data
   * @return tsData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "时间序列值-图表显示 suggested time-series data")

  public List<TsPair> getTsData() {
    return tsData;
  }


  public void setTsData(List<TsPair> tsData) {
    this.tsData = tsData;
  }


  public ControlItem unit(String unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * 单位 unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单位 unit")

  public String getUnit() {
    return unit;
  }


  public void setUnit(String unit) {
    this.unit = unit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControlItem controlItem = (ControlItem) o;
    return Objects.equals(this.itemName, controlItem.itemName) &&
        Objects.equals(this.suggestedValue, controlItem.suggestedValue) &&
        Objects.equals(this.tsData, controlItem.tsData) &&
        Objects.equals(this.unit, controlItem.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemName, suggestedValue, tsData, unit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControlItem {\n");
    sb.append("    itemName: ").append(toIndentedString(itemName)).append("\n");
    sb.append("    suggestedValue: ").append(toIndentedString(suggestedValue)).append("\n");
    sb.append("    tsData: ").append(toIndentedString(tsData)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

