/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * DeleteScenarioInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class DeleteScenarioInput {
  public static final String SERIALIZED_NAME_SCENARIO_IDS = "scenarioIds";
  @SerializedName(SERIALIZED_NAME_SCENARIO_IDS)
  private List<UUID> scenarioIds = null;


  public DeleteScenarioInput scenarioIds(List<UUID> scenarioIds) {
    
    this.scenarioIds = scenarioIds;
    return this;
  }

  public DeleteScenarioInput addScenarioIdsItem(UUID scenarioIdsItem) {
    if (this.scenarioIds == null) {
      this.scenarioIds = new ArrayList<UUID>();
    }
    this.scenarioIds.add(scenarioIdsItem);
    return this;
  }

   /**
   * 方案ID列表 scenario id list
   * @return scenarioIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "方案ID列表 scenario id list")

  public List<UUID> getScenarioIds() {
    return scenarioIds;
  }


  public void setScenarioIds(List<UUID> scenarioIds) {
    this.scenarioIds = scenarioIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteScenarioInput deleteScenarioInput = (DeleteScenarioInput) o;
    return Objects.equals(this.scenarioIds, deleteScenarioInput.scenarioIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scenarioIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteScenarioInput {\n");
    sb.append("    scenarioIds: ").append(toIndentedString(scenarioIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

