/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * DeviceMaintenanceOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class DeviceMaintenanceOutput {
  public static final String SERIALIZED_NAME_ONLINE_POINT = "onlinePoint";
  @SerializedName(SERIALIZED_NAME_ONLINE_POINT)
  private String onlinePoint;

  public static final String SERIALIZED_NAME_POINT_CODE = "pointCode";
  @SerializedName(SERIALIZED_NAME_POINT_CODE)
  private String pointCode;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private OffsetDateTime time;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private String location;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  private String tag;

  /**
   * Gets or Sets grade
   */
  @JsonAdapter(GradeEnum.Adapter.class)
  public enum GradeEnum {
    NUMBER_0(0),
    
    NUMBER_1(1),
    
    NUMBER_2(2);

    private Integer value;

    GradeEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static GradeEnum fromValue(Integer value) {
      for (GradeEnum b : GradeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<GradeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GradeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public GradeEnum read(final JsonReader jsonReader) throws IOException {
        Integer value =  jsonReader.nextInt();
        return GradeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_GRADE = "grade";
  @SerializedName(SERIALIZED_NAME_GRADE)
  private GradeEnum grade;


  public DeviceMaintenanceOutput onlinePoint(String onlinePoint) {
    
    this.onlinePoint = onlinePoint;
    return this;
  }

   /**
   * 在线点位名称 online point name
   * @return onlinePoint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "在线点位名称 online point name")

  public String getOnlinePoint() {
    return onlinePoint;
  }


  public void setOnlinePoint(String onlinePoint) {
    this.onlinePoint = onlinePoint;
  }


  public DeviceMaintenanceOutput pointCode(String pointCode) {
    
    this.pointCode = pointCode;
    return this;
  }

   /**
   * 在线点位代码 online point code
   * @return pointCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "在线点位代码 online point code")

  public String getPointCode() {
    return pointCode;
  }


  public void setPointCode(String pointCode) {
    this.pointCode = pointCode;
  }


  public DeviceMaintenanceOutput time(OffsetDateTime time) {
    
    this.time = time;
    return this;
  }

   /**
   * 时间 time
   * @return time
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "时间 time")

  public OffsetDateTime getTime() {
    return time;
  }


  public void setTime(OffsetDateTime time) {
    this.time = time;
  }


  public DeviceMaintenanceOutput location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * 位置 location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "位置 location")

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }


  public DeviceMaintenanceOutput status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * 维护预警状态 maintenance alarm status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "维护预警状态 maintenance alarm status")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public DeviceMaintenanceOutput message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * 维护预警信息 maintenance alarm message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "维护预警信息 maintenance alarm message")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public DeviceMaintenanceOutput label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * 设备状态标签 device status label
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "设备状态标签 device status label")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public DeviceMaintenanceOutput tag(String tag) {
    
    this.tag = tag;
    return this;
  }

   /**
   * 清洗标签 data clean tag
   * @return tag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "清洗标签 data clean tag")

  public String getTag() {
    return tag;
  }


  public void setTag(String tag) {
    this.tag = tag;
  }


  public DeviceMaintenanceOutput grade(GradeEnum grade) {
    
    this.grade = grade;
    return this;
  }

   /**
   * Get grade
   * @return grade
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GradeEnum getGrade() {
    return grade;
  }


  public void setGrade(GradeEnum grade) {
    this.grade = grade;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceMaintenanceOutput deviceMaintenanceOutput = (DeviceMaintenanceOutput) o;
    return Objects.equals(this.onlinePoint, deviceMaintenanceOutput.onlinePoint) &&
        Objects.equals(this.pointCode, deviceMaintenanceOutput.pointCode) &&
        Objects.equals(this.time, deviceMaintenanceOutput.time) &&
        Objects.equals(this.location, deviceMaintenanceOutput.location) &&
        Objects.equals(this.status, deviceMaintenanceOutput.status) &&
        Objects.equals(this.message, deviceMaintenanceOutput.message) &&
        Objects.equals(this.label, deviceMaintenanceOutput.label) &&
        Objects.equals(this.tag, deviceMaintenanceOutput.tag) &&
        Objects.equals(this.grade, deviceMaintenanceOutput.grade);
  }

  @Override
  public int hashCode() {
    return Objects.hash(onlinePoint, pointCode, time, location, status, message, label, tag, grade);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceMaintenanceOutput {\n");
    sb.append("    onlinePoint: ").append(toIndentedString(onlinePoint)).append("\n");
    sb.append("    pointCode: ").append(toIndentedString(pointCode)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    grade: ").append(toIndentedString(grade)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

