/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BioValue;
import org.threeten.bp.OffsetDateTime;

import java.time.LocalDateTime;

/**
 * EntireProcessTs
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class EntireProcessTs {
  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private LocalDateTime time;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private List<BioValue> data = null;

  public EntireProcessTs time(LocalDateTime time) {

    this.time = time;
    return this;
  }

  /**
   * 时间 time
   * 
   * @return time
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "时间 time")

  public LocalDateTime getTime() {
    return time;
  }

  public void setTime(LocalDateTime time) {
    this.time = time;
  }

  public EntireProcessTs data(List<BioValue> data) {

    this.data = data;
    return this;
  }

  public EntireProcessTs addDataItem(BioValue dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<BioValue>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * 全流程水质数据 data of each biochemical pool
   * 
   * @return data
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "全流程水质数据 data of each biochemical pool")

  public List<BioValue> getData() {
    return data;
  }

  public void setData(List<BioValue> data) {
    this.data = data;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntireProcessTs entireProcessTs = (EntireProcessTs) o;
    return Objects.equals(this.time, entireProcessTs.time) &&
        Objects.equals(this.data, entireProcessTs.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntireProcessTs {\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
