/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ControlItem;
import org.openapitools.client.model.PrecisionWq;

/**
 * ModelOptimDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class ModelOptimDto {
  public static final String SERIALIZED_NAME_CONTROL_ITEMS = "controlItems";
  @SerializedName(SERIALIZED_NAME_CONTROL_ITEMS)
  private List<ControlItem> controlItems = null;

  public static final String SERIALIZED_NAME_PRECISION_W_QS = "precisionWQs";
  @SerializedName(SERIALIZED_NAME_PRECISION_W_QS)
  private List<PrecisionWq> precisionWQs = null;


  public ModelOptimDto controlItems(List<ControlItem> controlItems) {
    
    this.controlItems = controlItems;
    return this;
  }

  public ModelOptimDto addControlItemsItem(ControlItem controlItemsItem) {
    if (this.controlItems == null) {
      this.controlItems = new ArrayList<ControlItem>();
    }
    this.controlItems.add(controlItemsItem);
    return this;
  }

   /**
   * 控制项数据 control item data
   * @return controlItems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "控制项数据 control item data")

  public List<ControlItem> getControlItems() {
    return controlItems;
  }


  public void setControlItems(List<ControlItem> controlItems) {
    this.controlItems = controlItems;
  }


  public ModelOptimDto precisionWQs(List<PrecisionWq> precisionWQs) {
    
    this.precisionWQs = precisionWQs;
    return this;
  }

  public ModelOptimDto addPrecisionWQsItem(PrecisionWq precisionWQsItem) {
    if (this.precisionWQs == null) {
      this.precisionWQs = new ArrayList<PrecisionWq>();
    }
    this.precisionWQs.add(precisionWQsItem);
    return this;
  }

   /**
   * 预测出水水质 effluent water quality data
   * @return precisionWQs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "预测出水水质 effluent water quality data")

  public List<PrecisionWq> getPrecisionWQs() {
    return precisionWQs;
  }


  public void setPrecisionWQs(List<PrecisionWq> precisionWQs) {
    this.precisionWQs = precisionWQs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelOptimDto modelOptimDto = (ModelOptimDto) o;
    return Objects.equals(this.controlItems, modelOptimDto.controlItems) &&
        Objects.equals(this.precisionWQs, modelOptimDto.precisionWQs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(controlItems, precisionWQs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelOptimDto {\n");
    sb.append("    controlItems: ").append(toIndentedString(controlItems)).append("\n");
    sb.append("    precisionWQs: ").append(toIndentedString(precisionWQs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

