/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * ModelPrecisionConfigsDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class ModelPrecisionConfigsDto {
  public static final String SERIALIZED_NAME_REGION_NAME = "regionName";
  @SerializedName(SERIALIZED_NAME_REGION_NAME)
  private String regionName;

  public static final String SERIALIZED_NAME_REC_PROBABILITY = "recProbability";
  @SerializedName(SERIALIZED_NAME_REC_PROBABILITY)
  private String recProbability;

  public static final String SERIALIZED_NAME_REGION_S_VALUE = "regionSValue";
  @SerializedName(SERIALIZED_NAME_REGION_S_VALUE)
  private Double regionSValue;

  public static final String SERIALIZED_NAME_REGION_E_VALUE = "regionEValue";
  @SerializedName(SERIALIZED_NAME_REGION_E_VALUE)
  private Double regionEValue;

  public static final String SERIALIZED_NAME_SORT = "sort";
  @SerializedName(SERIALIZED_NAME_SORT)
  private Integer sort;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private String unit;

  public static final String SERIALIZED_NAME_REC_PROBABILITY_S_VALUE = "recProbabilitySValue";
  @SerializedName(SERIALIZED_NAME_REC_PROBABILITY_S_VALUE)
  private Double recProbabilitySValue;

  public static final String SERIALIZED_NAME_REC_PROBABILITY_E_VALUE = "recProbabilityEValue";
  @SerializedName(SERIALIZED_NAME_REC_PROBABILITY_E_VALUE)
  private Double recProbabilityEValue;

  public static final String SERIALIZED_NAME_SCORE = "score";
  @SerializedName(SERIALIZED_NAME_SCORE)
  private Double score;

  public static final String SERIALIZED_NAME_LEVEL_CODE = "levelCode";
  @SerializedName(SERIALIZED_NAME_LEVEL_CODE)
  private String levelCode;

  public static final String SERIALIZED_NAME_REMARK = "remark";
  @SerializedName(SERIALIZED_NAME_REMARK)
  private String remark;


  public ModelPrecisionConfigsDto regionName(String regionName) {
    
    this.regionName = regionName;
    return this;
  }

   /**
   * 百分比区间名称,如:80-100(优秀) precision region name
   * @return regionName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "百分比区间名称,如:80-100(优秀) precision region name")

  public String getRegionName() {
    return regionName;
  }


  public void setRegionName(String regionName) {
    this.regionName = regionName;
  }


  public ModelPrecisionConfigsDto recProbability(String recProbability) {
    
    this.recProbability = recProbability;
    return this;
  }

   /**
   * 百分比区间推荐:如:&gt;70 precison region recommended proportion
   * @return recProbability
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "百分比区间推荐:如:>70 precison region recommended proportion")

  public String getRecProbability() {
    return recProbability;
  }


  public void setRecProbability(String recProbability) {
    this.recProbability = recProbability;
  }


  public ModelPrecisionConfigsDto regionSValue(Double regionSValue) {
    
    this.regionSValue = regionSValue;
    return this;
  }

   /**
   * 百分比区间开始,如:80 precision region start value
   * @return regionSValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "百分比区间开始,如:80 precision region start value")

  public Double getRegionSValue() {
    return regionSValue;
  }


  public void setRegionSValue(Double regionSValue) {
    this.regionSValue = regionSValue;
  }


  public ModelPrecisionConfigsDto regionEValue(Double regionEValue) {
    
    this.regionEValue = regionEValue;
    return this;
  }

   /**
   * 百分比区间截止,如:100 precision region end value
   * @return regionEValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "百分比区间截止,如:100 precision region end value")

  public Double getRegionEValue() {
    return regionEValue;
  }


  public void setRegionEValue(Double regionEValue) {
    this.regionEValue = regionEValue;
  }


  public ModelPrecisionConfigsDto sort(Integer sort) {
    
    this.sort = sort;
    return this;
  }

   /**
   * 排序号,越小越靠前 precision region index
   * @return sort
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "排序号,越小越靠前 precision region index")

  public Integer getSort() {
    return sort;
  }


  public void setSort(Integer sort) {
    this.sort = sort;
  }


  public ModelPrecisionConfigsDto code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * 指标 system point code
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "指标 system point code")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public ModelPrecisionConfigsDto id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * 配置ID config id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "配置ID config id")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public ModelPrecisionConfigsDto unit(String unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * 单位 unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单位 unit")

  public String getUnit() {
    return unit;
  }


  public void setUnit(String unit) {
    this.unit = unit;
  }


  public ModelPrecisionConfigsDto recProbabilitySValue(Double recProbabilitySValue) {
    
    this.recProbabilitySValue = recProbabilitySValue;
    return this;
  }

   /**
   * 推荐概率最小值，如70 minimum recommended proportion
   * @return recProbabilitySValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "推荐概率最小值，如70 minimum recommended proportion")

  public Double getRecProbabilitySValue() {
    return recProbabilitySValue;
  }


  public void setRecProbabilitySValue(Double recProbabilitySValue) {
    this.recProbabilitySValue = recProbabilitySValue;
  }


  public ModelPrecisionConfigsDto recProbabilityEValue(Double recProbabilityEValue) {
    
    this.recProbabilityEValue = recProbabilityEValue;
    return this;
  }

   /**
   * 推荐概率最大值，如100 maximum recommended proportion
   * @return recProbabilityEValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "推荐概率最大值，如100 maximum recommended proportion")

  public Double getRecProbabilityEValue() {
    return recProbabilityEValue;
  }


  public void setRecProbabilityEValue(Double recProbabilityEValue) {
    this.recProbabilityEValue = recProbabilityEValue;
  }


  public ModelPrecisionConfigsDto score(Double score) {
    
    this.score = score;
    return this;
  }

   /**
   * 得分 score
   * @return score
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "得分 score")

  public Double getScore() {
    return score;
  }


  public void setScore(Double score) {
    this.score = score;
  }


  public ModelPrecisionConfigsDto levelCode(String levelCode) {
    
    this.levelCode = levelCode;
    return this;
  }

   /**
   * 评价Code
   * @return levelCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "评价Code")

  public String getLevelCode() {
    return levelCode;
  }


  public void setLevelCode(String levelCode) {
    this.levelCode = levelCode;
  }


  public ModelPrecisionConfigsDto remark(String remark) {
    
    this.remark = remark;
    return this;
  }

   /**
   * 总体评价 overall evaluation
   * @return remark
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "总体评价 overall evaluation")

  public String getRemark() {
    return remark;
  }


  public void setRemark(String remark) {
    this.remark = remark;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelPrecisionConfigsDto modelPrecisionConfigsDto = (ModelPrecisionConfigsDto) o;
    return Objects.equals(this.regionName, modelPrecisionConfigsDto.regionName) &&
        Objects.equals(this.recProbability, modelPrecisionConfigsDto.recProbability) &&
        Objects.equals(this.regionSValue, modelPrecisionConfigsDto.regionSValue) &&
        Objects.equals(this.regionEValue, modelPrecisionConfigsDto.regionEValue) &&
        Objects.equals(this.sort, modelPrecisionConfigsDto.sort) &&
        Objects.equals(this.code, modelPrecisionConfigsDto.code) &&
        Objects.equals(this.id, modelPrecisionConfigsDto.id) &&
        Objects.equals(this.unit, modelPrecisionConfigsDto.unit) &&
        Objects.equals(this.recProbabilitySValue, modelPrecisionConfigsDto.recProbabilitySValue) &&
        Objects.equals(this.recProbabilityEValue, modelPrecisionConfigsDto.recProbabilityEValue) &&
        Objects.equals(this.score, modelPrecisionConfigsDto.score) &&
        Objects.equals(this.levelCode, modelPrecisionConfigsDto.levelCode) &&
        Objects.equals(this.remark, modelPrecisionConfigsDto.remark);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regionName, recProbability, regionSValue, regionEValue, sort, code, id, unit, recProbabilitySValue, recProbabilityEValue, score, levelCode, remark);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelPrecisionConfigsDto {\n");
    sb.append("    regionName: ").append(toIndentedString(regionName)).append("\n");
    sb.append("    recProbability: ").append(toIndentedString(recProbability)).append("\n");
    sb.append("    regionSValue: ").append(toIndentedString(regionSValue)).append("\n");
    sb.append("    regionEValue: ").append(toIndentedString(regionEValue)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    recProbabilitySValue: ").append(toIndentedString(recProbabilitySValue)).append("\n");
    sb.append("    recProbabilityEValue: ").append(toIndentedString(recProbabilityEValue)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    levelCode: ").append(toIndentedString(levelCode)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

