/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.TsPair;

/**
 * OutletWqOut
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class OutletWqOut {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_REAL_DATAS = "realDatas";
  @SerializedName(SERIALIZED_NAME_REAL_DATAS)
  private List<TsPair> realDatas = null;

  public static final String SERIALIZED_NAME_MODEL_DATAS = "modelDatas";
  @SerializedName(SERIALIZED_NAME_MODEL_DATAS)
  private List<TsPair> modelDatas = null;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private String unit;


  public OutletWqOut code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * 指标 indicator code
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "指标 indicator code")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public OutletWqOut realDatas(List<TsPair> realDatas) {
    
    this.realDatas = realDatas;
    return this;
  }

  public OutletWqOut addRealDatasItem(TsPair realDatasItem) {
    if (this.realDatas == null) {
      this.realDatas = new ArrayList<TsPair>();
    }
    this.realDatas.add(realDatasItem);
    return this;
  }

   /**
   * 在线数据 online data
   * @return realDatas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "在线数据 online data")

  public List<TsPair> getRealDatas() {
    return realDatas;
  }


  public void setRealDatas(List<TsPair> realDatas) {
    this.realDatas = realDatas;
  }


  public OutletWqOut modelDatas(List<TsPair> modelDatas) {
    
    this.modelDatas = modelDatas;
    return this;
  }

  public OutletWqOut addModelDatasItem(TsPair modelDatasItem) {
    if (this.modelDatas == null) {
      this.modelDatas = new ArrayList<TsPair>();
    }
    this.modelDatas.add(modelDatasItem);
    return this;
  }

   /**
   * 模拟数据 model result data
   * @return modelDatas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "模拟数据 model result data")

  public List<TsPair> getModelDatas() {
    return modelDatas;
  }


  public void setModelDatas(List<TsPair> modelDatas) {
    this.modelDatas = modelDatas;
  }


  public OutletWqOut unit(String unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * 单位 unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单位 unit")

  public String getUnit() {
    return unit;
  }


  public void setUnit(String unit) {
    this.unit = unit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutletWqOut outletWqOut = (OutletWqOut) o;
    return Objects.equals(this.code, outletWqOut.code) &&
        Objects.equals(this.realDatas, outletWqOut.realDatas) &&
        Objects.equals(this.modelDatas, outletWqOut.modelDatas) &&
        Objects.equals(this.unit, outletWqOut.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, realDatas, modelDatas, unit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutletWqOut {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    realDatas: ").append(toIndentedString(realDatas)).append("\n");
    sb.append("    modelDatas: ").append(toIndentedString(modelDatas)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

