/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SelectItemNodeDetailInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class SelectItemNodeDetailInfo {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private String unit;

  public static final String SERIALIZED_NAME_ONLINE_CODE = "onlineCode";
  @SerializedName(SERIALIZED_NAME_ONLINE_CODE)
  private String onlineCode;

  public static final String SERIALIZED_NAME_MODEL_CODE = "modelCode";
  @SerializedName(SERIALIZED_NAME_MODEL_CODE)
  private String modelCode;

  public static final String SERIALIZED_NAME_MODEL_DATA_TYPE = "modelDataType";
  @SerializedName(SERIALIZED_NAME_MODEL_DATA_TYPE)
  private String modelDataType;


  public SelectItemNodeDetailInfo code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public SelectItemNodeDetailInfo unit(String unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUnit() {
    return unit;
  }


  public void setUnit(String unit) {
    this.unit = unit;
  }


  public SelectItemNodeDetailInfo onlineCode(String onlineCode) {
    
    this.onlineCode = onlineCode;
    return this;
  }

   /**
   * Get onlineCode
   * @return onlineCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOnlineCode() {
    return onlineCode;
  }


  public void setOnlineCode(String onlineCode) {
    this.onlineCode = onlineCode;
  }


  public SelectItemNodeDetailInfo modelCode(String modelCode) {
    
    this.modelCode = modelCode;
    return this;
  }

   /**
   * Get modelCode
   * @return modelCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getModelCode() {
    return modelCode;
  }


  public void setModelCode(String modelCode) {
    this.modelCode = modelCode;
  }


  public SelectItemNodeDetailInfo modelDataType(String modelDataType) {
    
    this.modelDataType = modelDataType;
    return this;
  }

   /**
   * Get modelDataType
   * @return modelDataType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getModelDataType() {
    return modelDataType;
  }


  public void setModelDataType(String modelDataType) {
    this.modelDataType = modelDataType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectItemNodeDetailInfo selectItemNodeDetailInfo = (SelectItemNodeDetailInfo) o;
    return Objects.equals(this.code, selectItemNodeDetailInfo.code) &&
        Objects.equals(this.unit, selectItemNodeDetailInfo.unit) &&
        Objects.equals(this.onlineCode, selectItemNodeDetailInfo.onlineCode) &&
        Objects.equals(this.modelCode, selectItemNodeDetailInfo.modelCode) &&
        Objects.equals(this.modelDataType, selectItemNodeDetailInfo.modelDataType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, unit, onlineCode, modelCode, modelDataType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectItemNodeDetailInfo {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    onlineCode: ").append(toIndentedString(onlineCode)).append("\n");
    sb.append("    modelCode: ").append(toIndentedString(modelCode)).append("\n");
    sb.append("    modelDataType: ").append(toIndentedString(modelDataType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

