/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.TsPair;

/**
 * SimResultsOutupt
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class SimResultsOutupt {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_OUT_WATERS_UNIT = "outWatersUnit";
  @SerializedName(SERIALIZED_NAME_OUT_WATERS_UNIT)
  private String outWatersUnit;

  public static final String SERIALIZED_NAME_OUT_WATERS = "outWaters";
  @SerializedName(SERIALIZED_NAME_OUT_WATERS)
  private List<TsPair> outWaters = null;


  public SimResultsOutupt code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * 指标代码 indicator code
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "指标代码 indicator code")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public SimResultsOutupt outWatersUnit(String outWatersUnit) {
    
    this.outWatersUnit = outWatersUnit;
    return this;
  }

   /**
   * 指标单位 indicator unit
   * @return outWatersUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "指标单位 indicator unit")

  public String getOutWatersUnit() {
    return outWatersUnit;
  }


  public void setOutWatersUnit(String outWatersUnit) {
    this.outWatersUnit = outWatersUnit;
  }


  public SimResultsOutupt outWaters(List<TsPair> outWaters) {
    
    this.outWaters = outWaters;
    return this;
  }

  public SimResultsOutupt addOutWatersItem(TsPair outWatersItem) {
    if (this.outWaters == null) {
      this.outWaters = new ArrayList<TsPair>();
    }
    this.outWaters.add(outWatersItem);
    return this;
  }

   /**
   * 时间序列数据 time-series data
   * @return outWaters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "时间序列数据 time-series data")

  public List<TsPair> getOutWaters() {
    return outWaters;
  }


  public void setOutWaters(List<TsPair> outWaters) {
    this.outWaters = outWaters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimResultsOutupt simResultsOutupt = (SimResultsOutupt) o;
    return Objects.equals(this.code, simResultsOutupt.code) &&
        Objects.equals(this.outWatersUnit, simResultsOutupt.outWatersUnit) &&
        Objects.equals(this.outWaters, simResultsOutupt.outWaters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, outWatersUnit, outWaters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimResultsOutupt {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    outWatersUnit: ").append(toIndentedString(outWatersUnit)).append("\n");
    sb.append("    outWaters: ").append(toIndentedString(outWaters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

