/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ExpressionInfo;
import org.openapitools.client.model.SvrPointInfo;

/**
 * SysStatisticConfigs表的StatisticVarRef字段(存储JSON字符串)
 */
@ApiModel(description = "SysStatisticConfigs表的StatisticVarRef字段(存储JSON字符串)")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class StatisticVarRefDto {
  public static final String SERIALIZED_NAME_POINT_INFOS = "pointInfos";
  @SerializedName(SERIALIZED_NAME_POINT_INFOS)
  private List<SvrPointInfo> pointInfos = null;

  public static final String SERIALIZED_NAME_EXPRESSION = "expression";
  @SerializedName(SERIALIZED_NAME_EXPRESSION)
  private ExpressionInfo expression;


  public StatisticVarRefDto pointInfos(List<SvrPointInfo> pointInfos) {
    
    this.pointInfos = pointInfos;
    return this;
  }

  public StatisticVarRefDto addPointInfosItem(SvrPointInfo pointInfosItem) {
    if (this.pointInfos == null) {
      this.pointInfos = new ArrayList<SvrPointInfo>();
    }
    this.pointInfos.add(pointInfosItem);
    return this;
  }

   /**
   * 点位
   * @return pointInfos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "点位")

  public List<SvrPointInfo> getPointInfos() {
    return pointInfos;
  }


  public void setPointInfos(List<SvrPointInfo> pointInfos) {
    this.pointInfos = pointInfos;
  }


  public StatisticVarRefDto expression(ExpressionInfo expression) {
    
    this.expression = expression;
    return this;
  }

   /**
   * Get expression
   * @return expression
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpressionInfo getExpression() {
    return expression;
  }


  public void setExpression(ExpressionInfo expression) {
    this.expression = expression;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticVarRefDto statisticVarRefDto = (StatisticVarRefDto) o;
    return Objects.equals(this.pointInfos, statisticVarRefDto.pointInfos) &&
        Objects.equals(this.expression, statisticVarRefDto.expression);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pointInfos, expression);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticVarRefDto {\n");
    sb.append("    pointInfos: ").append(toIndentedString(pointInfos)).append("\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

