/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * StatisticData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class StatisticData {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private String unit;

  public static final String SERIALIZED_NAME_MIN = "min";
  @SerializedName(SERIALIZED_NAME_MIN)
  private Double min;

  public static final String SERIALIZED_NAME_MAX = "max";
  @SerializedName(SERIALIZED_NAME_MAX)
  private Double max;

  public static final String SERIALIZED_NAME_MEAN = "mean";
  @SerializedName(SERIALIZED_NAME_MEAN)
  private Double mean;

  public static final String SERIALIZED_NAME_ONLINE = "online";
  @SerializedName(SERIALIZED_NAME_ONLINE)
  private Double online;


  public StatisticData code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * 指标 indicator
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "指标 indicator")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public StatisticData unit(String unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * 单位 unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单位 unit")

  public String getUnit() {
    return unit;
  }


  public void setUnit(String unit) {
    this.unit = unit;
  }


  public StatisticData min(Double min) {
    
    this.min = min;
    return this;
  }

   /**
   * 最小值 minimum value
   * @return min
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "最小值 minimum value")

  public Double getMin() {
    return min;
  }


  public void setMin(Double min) {
    this.min = min;
  }


  public StatisticData max(Double max) {
    
    this.max = max;
    return this;
  }

   /**
   * 最大值 maximum value
   * @return max
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "最大值 maximum value")

  public Double getMax() {
    return max;
  }


  public void setMax(Double max) {
    this.max = max;
  }


  public StatisticData mean(Double mean) {
    
    this.mean = mean;
    return this;
  }

   /**
   * 平均值 average value
   * @return mean
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "平均值 average value")

  public Double getMean() {
    return mean;
  }


  public void setMean(Double mean) {
    this.mean = mean;
  }


  public StatisticData online(Double online) {
    
    this.online = online;
    return this;
  }

   /**
   * 在线值 online value if existed
   * @return online
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "在线值 online value if existed")

  public Double getOnline() {
    return online;
  }


  public void setOnline(Double online) {
    this.online = online;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticData statisticData = (StatisticData) o;
    return Objects.equals(this.code, statisticData.code) &&
        Objects.equals(this.unit, statisticData.unit) &&
        Objects.equals(this.min, statisticData.min) &&
        Objects.equals(this.max, statisticData.max) &&
        Objects.equals(this.mean, statisticData.mean) &&
        Objects.equals(this.online, statisticData.online);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, unit, min, max, mean, online);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticData {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    mean: ").append(toIndentedString(mean)).append("\n");
    sb.append("    online: ").append(toIndentedString(online)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

