/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * SysStatisticConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class SysStatisticConfig {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private UUID tenantId;

  public static final String SERIALIZED_NAME_STATISTIC_CODE = "statisticCode";
  @SerializedName(SERIALIZED_NAME_STATISTIC_CODE)
  private String statisticCode;

  public static final String SERIALIZED_NAME_STATISTIC_NAME = "statisticName";
  @SerializedName(SERIALIZED_NAME_STATISTIC_NAME)
  private String statisticName;

  /**
   * Gets or Sets statisticType
   */
  @JsonAdapter(StatisticTypeEnum.Adapter.class)
  public enum StatisticTypeEnum {
    NUMBER_0(0),
    
    NUMBER_1(1),
    
    NUMBER_2(2);

    private Integer value;

    StatisticTypeEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatisticTypeEnum fromValue(Integer value) {
      for (StatisticTypeEnum b : StatisticTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatisticTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatisticTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatisticTypeEnum read(final JsonReader jsonReader) throws IOException {
        Integer value =  jsonReader.nextInt();
        return StatisticTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATISTIC_TYPE = "statisticType";
  @SerializedName(SERIALIZED_NAME_STATISTIC_TYPE)
  private StatisticTypeEnum statisticType;

  public static final String SERIALIZED_NAME_STATISTIC_VAR_REF = "statisticVarRef";
  @SerializedName(SERIALIZED_NAME_STATISTIC_VAR_REF)
  private String statisticVarRef;

  public static final String SERIALIZED_NAME_CREATION_TIME = "creationTime";
  @SerializedName(SERIALIZED_NAME_CREATION_TIME)
  private OffsetDateTime creationTime;

  public static final String SERIALIZED_NAME_IS_DISPLAY = "isDisplay";
  @SerializedName(SERIALIZED_NAME_IS_DISPLAY)
  private Boolean isDisplay;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private String unit;

  public static final String SERIALIZED_NAME_GROUP_NAME = "groupName";
  @SerializedName(SERIALIZED_NAME_GROUP_NAME)
  private String groupName;


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getId() {
    return id;
  }




  public SysStatisticConfig tenantId(UUID tenantId) {
    
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getTenantId() {
    return tenantId;
  }


  public void setTenantId(UUID tenantId) {
    this.tenantId = tenantId;
  }


  public SysStatisticConfig statisticCode(String statisticCode) {
    
    this.statisticCode = statisticCode;
    return this;
  }

   /**
   * Get statisticCode
   * @return statisticCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatisticCode() {
    return statisticCode;
  }


  public void setStatisticCode(String statisticCode) {
    this.statisticCode = statisticCode;
  }


  public SysStatisticConfig statisticName(String statisticName) {
    
    this.statisticName = statisticName;
    return this;
  }

   /**
   * Get statisticName
   * @return statisticName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatisticName() {
    return statisticName;
  }


  public void setStatisticName(String statisticName) {
    this.statisticName = statisticName;
  }


  public SysStatisticConfig statisticType(StatisticTypeEnum statisticType) {
    
    this.statisticType = statisticType;
    return this;
  }

   /**
   * Get statisticType
   * @return statisticType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public StatisticTypeEnum getStatisticType() {
    return statisticType;
  }


  public void setStatisticType(StatisticTypeEnum statisticType) {
    this.statisticType = statisticType;
  }


  public SysStatisticConfig statisticVarRef(String statisticVarRef) {
    
    this.statisticVarRef = statisticVarRef;
    return this;
  }

   /**
   * Get statisticVarRef
   * @return statisticVarRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatisticVarRef() {
    return statisticVarRef;
  }


  public void setStatisticVarRef(String statisticVarRef) {
    this.statisticVarRef = statisticVarRef;
  }


  public SysStatisticConfig creationTime(OffsetDateTime creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreationTime() {
    return creationTime;
  }


  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }


  public SysStatisticConfig isDisplay(Boolean isDisplay) {
    
    this.isDisplay = isDisplay;
    return this;
  }

   /**
   * Get isDisplay
   * @return isDisplay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsDisplay() {
    return isDisplay;
  }


  public void setIsDisplay(Boolean isDisplay) {
    this.isDisplay = isDisplay;
  }


  public SysStatisticConfig unit(String unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUnit() {
    return unit;
  }


  public void setUnit(String unit) {
    this.unit = unit;
  }


  public SysStatisticConfig groupName(String groupName) {
    
    this.groupName = groupName;
    return this;
  }

   /**
   * Get groupName
   * @return groupName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGroupName() {
    return groupName;
  }


  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SysStatisticConfig sysStatisticConfig = (SysStatisticConfig) o;
    return Objects.equals(this.id, sysStatisticConfig.id) &&
        Objects.equals(this.tenantId, sysStatisticConfig.tenantId) &&
        Objects.equals(this.statisticCode, sysStatisticConfig.statisticCode) &&
        Objects.equals(this.statisticName, sysStatisticConfig.statisticName) &&
        Objects.equals(this.statisticType, sysStatisticConfig.statisticType) &&
        Objects.equals(this.statisticVarRef, sysStatisticConfig.statisticVarRef) &&
        Objects.equals(this.creationTime, sysStatisticConfig.creationTime) &&
        Objects.equals(this.isDisplay, sysStatisticConfig.isDisplay) &&
        Objects.equals(this.unit, sysStatisticConfig.unit) &&
        Objects.equals(this.groupName, sysStatisticConfig.groupName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tenantId, statisticCode, statisticName, statisticType, statisticVarRef, creationTime, isDisplay, unit, groupName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SysStatisticConfig {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    statisticCode: ").append(toIndentedString(statisticCode)).append("\n");
    sb.append("    statisticName: ").append(toIndentedString(statisticName)).append("\n");
    sb.append("    statisticType: ").append(toIndentedString(statisticType)).append("\n");
    sb.append("    statisticVarRef: ").append(toIndentedString(statisticVarRef)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    isDisplay: ").append(toIndentedString(isDisplay)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

