/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * TsDataOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class TsDataOutput {
  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private OffsetDateTime time;

  public static final String SERIALIZED_NAME_POINT_CODE = "pointCode";
  @SerializedName(SERIALIZED_NAME_POINT_CODE)
  private String pointCode;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private Double value;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  private String tag;


  public TsDataOutput time(OffsetDateTime time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getTime() {
    return time;
  }


  public void setTime(OffsetDateTime time) {
    this.time = time;
  }


  public TsDataOutput pointCode(String pointCode) {
    
    this.pointCode = pointCode;
    return this;
  }

   /**
   * 点位编码 point code
   * @return pointCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "点位编码 point code")

  public String getPointCode() {
    return pointCode;
  }


  public void setPointCode(String pointCode) {
    this.pointCode = pointCode;
  }


  public TsDataOutput value(Double value) {
    
    this.value = value;
    return this;
  }

   /**
   * 值 value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "值 value")

  public Double getValue() {
    return value;
  }


  public void setValue(Double value) {
    this.value = value;
  }


  public TsDataOutput tag(String tag) {
    
    this.tag = tag;
    return this;
  }

   /**
   * 标记 data clean tag
   * @return tag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "标记 data clean tag")

  public String getTag() {
    return tag;
  }


  public void setTag(String tag) {
    this.tag = tag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TsDataOutput tsDataOutput = (TsDataOutput) o;
    return Objects.equals(this.time, tsDataOutput.time) &&
        Objects.equals(this.pointCode, tsDataOutput.pointCode) &&
        Objects.equals(this.value, tsDataOutput.value) &&
        Objects.equals(this.tag, tsDataOutput.tag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, pointCode, value, tag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TsDataOutput {\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    pointCode: ").append(toIndentedString(pointCode)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

