/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * WqOnlineDataInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class WqOnlineDataInput {
  public static final String SERIALIZED_NAME_POINT_CODES = "pointCodes";
  @SerializedName(SERIALIZED_NAME_POINT_CODES)
  private List<String> pointCodes = null;

  public static final String SERIALIZED_NAME_START_TIME = "startTime";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  private OffsetDateTime startTime;

  public static final String SERIALIZED_NAME_END_TIME = "endTime";
  @SerializedName(SERIALIZED_NAME_END_TIME)
  private OffsetDateTime endTime;


  public WqOnlineDataInput pointCodes(List<String> pointCodes) {
    
    this.pointCodes = pointCodes;
    return this;
  }

  public WqOnlineDataInput addPointCodesItem(String pointCodesItem) {
    if (this.pointCodes == null) {
      this.pointCodes = new ArrayList<String>();
    }
    this.pointCodes.add(pointCodesItem);
    return this;
  }

   /**
   * 在线点位列表 online point code list
   * @return pointCodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "在线点位列表 online point code list")

  public List<String> getPointCodes() {
    return pointCodes;
  }


  public void setPointCodes(List<String> pointCodes) {
    this.pointCodes = pointCodes;
  }


  public WqOnlineDataInput startTime(OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * 开始时间 start time
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "开始时间 start time")

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public WqOnlineDataInput endTime(OffsetDateTime endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * 结束时间 end time
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "结束时间 end time")

  public OffsetDateTime getEndTime() {
    return endTime;
  }


  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WqOnlineDataInput wqOnlineDataInput = (WqOnlineDataInput) o;
    return Objects.equals(this.pointCodes, wqOnlineDataInput.pointCodes) &&
        Objects.equals(this.startTime, wqOnlineDataInput.startTime) &&
        Objects.equals(this.endTime, wqOnlineDataInput.endTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pointCodes, startTime, endTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WqOnlineDataInput {\n");
    sb.append("    pointCodes: ").append(toIndentedString(pointCodes)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

