/*
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * WqSimulationIndicatorInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-09T14:11:26.479568400+08:00[Asia/Shanghai]")
public class WqSimulationIndicatorInput {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_IS_DISPLAY = "isDisplay";
  @SerializedName(SERIALIZED_NAME_IS_DISPLAY)
  private Boolean isDisplay;


  public WqSimulationIndicatorInput id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * 指标ID indicator id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "指标ID indicator id")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public WqSimulationIndicatorInput isDisplay(Boolean isDisplay) {
    
    this.isDisplay = isDisplay;
    return this;
  }

   /**
   * 是否展示 if display at the front end
   * @return isDisplay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "是否展示 if display at the front end")

  public Boolean getIsDisplay() {
    return isDisplay;
  }


  public void setIsDisplay(Boolean isDisplay) {
    this.isDisplay = isDisplay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WqSimulationIndicatorInput wqSimulationIndicatorInput = (WqSimulationIndicatorInput) o;
    return Objects.equals(this.id, wqSimulationIndicatorInput.id) &&
        Objects.equals(this.isDisplay, wqSimulationIndicatorInput.isDisplay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, isDisplay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WqSimulationIndicatorInput {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isDisplay: ").append(toIndentedString(isDisplay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

