name: publish jar to Maven

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pre -checkout 
        run: |
            pwd
            ls -lh
      - name: checkout code
        uses: actions/checkout@v3
      - name: after -checkout 
        run: |
            pwd
            ls -lh
      - name: Setup JAVA
        uses: actions/setup-java@v1
        with:
            java-version: 11         
            server-username: ${{ secrets.OSSRH_USER }}
            server-password: ${{ secrets.OSSRH_PASSWORD }}
            gpg-passphrase:  ${{ secrets.GPG_PASSWORD }}

      - name: Publish to Maven Central Repo
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus_username: ${{ secrets.OSSRH_USER }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}

